name: 部署文档至 gh-pages 分支

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: 设置 Node.js 版本
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: 安装依赖
        run: |
          pnpm config set verify-deps-before-run false
          pnpm install --frozen-lockfile --no-verify-store-integrity

      - name: 构建文档中
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm docs:build

      - name: 部署至 gh-pages 分支中
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
          single-commit: true